import {
  User,
  Student,
  Teacher,
  Parent,
  SchoolClass,
  Subject,
  AttendanceRecord,
  TahfizRecord,
  GradeRecord,
  AssessmentConfig,
  ResultApprovalSubmission,
  Announcement,
  SchoolSession,
  Programme,
  TimetablePeriod,
  DirectMessage,
} from '../types';
import { hashPassword } from './security';

export const CURRENT_SESSION: SchoolSession = {
  id: 'sess-01',
  sessionName: '1447/1448 AH (2025/2026 AD)',
  activeTerm: 'Term 2',
  isCurrent: true,
};

export const MOCK_PROGRAMMES: Programme[] = [
  {
    id: 'prog-01',
    programme_name_english: 'Asubah & Magrib',
    programme_name_arabic: 'الصباح والمغرب',
    programme_name: 'Asubah & Magrib',
    programme_code: 'ASM',
    description: 'Morning & Evening Quranic Memorization & Islamic Studies Program',
    status: 'Active',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'prog-02',
    programme_name_english: 'Super Markaz',
    programme_name_arabic: 'سوبر مركز',
    programme_name: 'Super Markaz',
    programme_code: 'SPM',
    description: 'Advanced Intensive Full-Time Quranic Tahfiz & Shariah Studies',
    status: 'Active',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'prog-03',
    programme_name_english: 'Islamiyyah',
    programme_name_arabic: 'الإسلامية',
    programme_name: 'Islamiyyah',
    programme_code: 'ISM',
    description: 'Standard Primary & Secondary Islamiyyah Stream',
    status: 'Active',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'prog-04',
    programme_name_english: 'Matan Aure',
    programme_name_arabic: 'متن الزوجية',
    programme_name: 'Matan Aure',
    programme_code: 'MTA',
    description: "Specialized Marital & Women's Islamic Guidance Studies",
    status: 'Active',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'usr-superadmin-1',
    name: 'Dr. Abubakar Umar (Super Admin)',
    email: 'elmuaztechnologiesltd@gmail.com',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    phone: '+234 816 710 9421',
    status: 'ACTIVE',
    passwordHash: hashPassword('admin123'),
    isFirstLogin: false,
    isLocked: false,
    failedLoginAttempts: 0,
    lastLoginAt: new Date().toLocaleString(),
  },
  {
    id: 'usr-admin-1',
    name: 'Malam Umar Faruq (School Admin)',
    email: 'elmuaztechnologiesltd@gmail.com',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+234 803 123 4567',
    status: 'ACTIVE',
    passwordHash: hashPassword('admin123'),
    isFirstLogin: false,
    isLocked: false,
    failedLoginAttempts: 0,
    lastLoginAt: new Date().toLocaleString(),
  },
  {
    id: 'usr-teacher-1',
    name: 'Ustaz Abubakar Sadiq',
    email: 'elmuaztechnologiesltd@gmail.com',
    role: 'TEACHER',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+234 802 234 5678',
    status: 'ACTIVE',
    passwordHash: hashPassword('admin123'),
    isFirstLogin: false,
    isLocked: false,
    failedLoginAttempts: 0,
    lastLoginAt: new Date().toLocaleString(),
  },
  {
    id: 'usr-student-1',
    name: 'Ibrahim Kabir Ahmad',
    email: 'student@markazuumar.edu.ng',
    role: 'STUDENT',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    phone: '+234 809 345 6789',
    status: 'ACTIVE',
    passwordHash: hashPassword('admin123'),
    isFirstLogin: false,
    isLocked: false,
    failedLoginAttempts: 0,
    lastLoginAt: new Date().toLocaleString(),
  },
  {
    id: 'usr-parent-1',
    name: 'Alhaji Kabir Ahmad',
    email: 'parent@markazuumar.edu.ng',
    role: 'PARENT',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+234 803 987 6543',
    status: 'ACTIVE',
    passwordHash: hashPassword('admin123'),
    isFirstLogin: false,
    isLocked: false,
    failedLoginAttempts: 0,
    lastLoginAt: new Date().toLocaleString(),
  },
];

export const MOCK_CLASSES: SchoolClass[] = [
  {
    id: 'cls-asm-1',
    class_name_english: 'Dar Abu Bakr As-Siddiq',
    class_name_arabic: 'دار أبي بكر الصديق',
    name: 'Dar Abu Bakr As-Siddiq',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 24,
    classTeacherId: 'usr-teacher-asm-1',
    classTeacherName: 'Abdullahi Sulaiman Abubakar',
    classTeacherNameArabic: 'عبدالله سليمان أبوبكر',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-2',
    class_name_english: 'Dar Umar ibn Al-Khattab',
    class_name_arabic: 'دار عمر بن الخطاب',
    name: 'Dar Umar ibn Al-Khattab',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 22,
    classTeacherId: 'usr-teacher-asm-2',
    classTeacherName: 'Muhammad Sani Luqman',
    classTeacherNameArabic: 'محمد ثاني لقمان',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-3',
    class_name_english: 'Dar Uthman ibn Affan',
    class_name_arabic: 'دار عثمان بن عفان',
    name: 'Dar Uthman ibn Affan',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 25,
    classTeacherId: 'usr-teacher-asm-3',
    classTeacherName: "Abdullahi Da'i Muhammad",
    classTeacherNameArabic: 'عبدالله داعى محمد',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-4',
    class_name_english: 'Dar Ali ibn Abi Talib',
    class_name_arabic: 'دار علي بن أبي طالب',
    name: 'Dar Ali ibn Abi Talib',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 20,
    classTeacherId: 'usr-teacher-asm-4',
    classTeacherName: 'Yusuf Sanusi',
    classTeacherNameArabic: 'يوسف سنوسي',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-5',
    class_name_english: 'Abdul Rahman ibn Awf',
    class_name_arabic: 'عبد الرحمن بن عوف',
    name: 'Abdul Rahman ibn Awf',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 18,
    classTeacherId: 'usr-teacher-asm-5',
    classTeacherName: 'Ammar Munir Ibrahim',
    classTeacherNameArabic: 'عمار منير إبراهيم',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-6',
    class_name_english: 'Talhah ibn Ubaydillah',
    class_name_arabic: 'طلحة بن عبيد الله',
    name: 'Talhah ibn Ubaydillah',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 26,
    classTeacherId: 'usr-teacher-asm-6',
    classTeacherName: 'Fatima Abdulhadi',
    classTeacherNameArabic: 'فاطمة عبد الهادي',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-7',
    class_name_english: 'Az-Zubayr ibn Al-Awwam',
    class_name_arabic: 'زبير بن العوام',
    name: 'Az-Zubayr ibn Al-Awwam',
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 21,
    classTeacherId: 'usr-teacher-asm-7',
    classTeacherName: 'Amina Ali',
    classTeacherNameArabic: 'آمنة علي',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-8',
    class_name_english: "Sa'd ibn Abi Waqqas",
    class_name_arabic: 'سعد بن أبي وقاص',
    name: "Sa'd ibn Abi Waqqas",
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 19,
    classTeacherId: 'usr-teacher-asm-8',
    classTeacherName: 'Hasana Ali',
    classTeacherNameArabic: 'حسنة علي',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-asm-9',
    class_name_english: "Sa'id ibn Zayd",
    class_name_arabic: 'سعيد بن زيد',
    name: "Sa'id ibn Zayd",
    category: 'TAHFIZ',
    section: 'Asubah & Magrib Stream',
    capacity: 30,
    studentCount: 23,
    classTeacherId: 'usr-teacher-asm-9',
    classTeacherName: "Usama Rabi'",
    classTeacherNameArabic: 'أسامة رابع',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    programmeNameArabic: 'الصباح والمغرب',
  },
  {
    id: 'cls-tahfiz-1',
    class_name_english: 'Tahfiz Halqa 1 (Advanced Hifz)',
    class_name_arabic: 'حلقة التحفيظ 1',
    name: 'Tahfiz Halqa 1 (Advanced Hifz)',
    category: 'TAHFIZ',
    section: 'Halqa A',
    capacity: 25,
    studentCount: 22,
    classTeacherId: 'usr-teacher-1',
    classTeacherName: 'Ustaz Abubakar Sadiq',
    classTeacherNameArabic: 'أستاذ أبوبكر الصديق',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    programmeNameArabic: 'سوبر مركز',
  },
  {
    id: 'cls-tahfiz-2',
    class_name_english: 'Tahfiz Halqa 2 (Intermediate Hifz)',
    class_name_arabic: 'حلقة التحفيظ 2',
    name: 'Tahfiz Halqa 2 (Intermediate Hifz)',
    category: 'TAHFIZ',
    section: 'Halqa B',
    capacity: 25,
    studentCount: 20,
    classTeacherId: 'usr-teacher-2',
    classTeacherName: 'Ustaz Usman Danfodio',
    classTeacherNameArabic: 'أستاذ عثمان دَن فودي',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    programmeNameArabic: 'سوبر مركز',
  },
  {
    id: 'cls-primary-4',
    class_name_english: 'Primary 4 Islamiyya',
    class_name_arabic: 'الابتدائية 4 الإسلامية',
    name: 'Primary 4 Islamiyya',
    category: 'ISLAMIYYA_PRIMARY',
    section: 'Section A',
    capacity: 35,
    studentCount: 32,
    classTeacherId: 'usr-teacher-3',
    classTeacherName: 'Malama Aishatu Bello',
    classTeacherNameArabic: 'معلمة عائشة بيلو',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    programmeNameArabic: 'الإسلامية',
  },
  {
    id: 'cls-secondary-2',
    class_name_english: 'Secondary 2 Islamiyya',
    class_name_arabic: 'الإعدادية 2 الإسلامية',
    name: 'Secondary 2 Islamiyya',
    category: 'ISLAMIYYA_SECONDARY',
    section: 'Section B',
    capacity: 35,
    studentCount: 30,
    classTeacherId: 'usr-teacher-4',
    classTeacherName: 'Ustaz Idris Al-Kashnawi',
    classTeacherNameArabic: 'أستاذ إدريس الكشناوي',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    programmeNameArabic: 'الإسلامية',
  },
  {
    id: 'cls-matan-1',
    class_name_english: 'Matan Aure Women Circle 1',
    class_name_arabic: 'حلقة متن الزوجية 1',
    name: 'Matan Aure Women Circle 1',
    category: 'ISLAMIYYA_PRIMARY',
    section: 'Weekend Session',
    capacity: 40,
    studentCount: 35,
    classTeacherId: 'usr-teacher-3',
    classTeacherName: 'Malama Aishatu Bello',
    classTeacherNameArabic: 'معلمة عائشة بيلو',
    programmeId: 'prog-04',
    programmeName: 'Matan Aure',
    programmeNameArabic: 'متن الزوجية',
  },
];



export const MOCK_STUDENTS: Student[] = [
  {
    id: 'usr-student-1',
    admissionNo: 'MU-2023-0142',
    fullName: 'Ibrahim Kabir Ahmad',
    gender: 'MALE',
    dob: '2012-05-14',
    dateEnrolled: '2023-09-01',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    guardianId: 'usr-parent-1',
    guardianName: 'Alhaji Kabir Ahmad',
    guardianPhone: '+234 803 987 6543',
    status: 'ACTIVE',
    hifzProgress: {
      currentJuz: 18,
      juzCompleted: 17,
      currentSurah: 'Surah Al-Kahf',
      currentAyah: 45,
      completedSurahsCount: 48,
      tajweedRating: 5,
      sabkiRating: 4,
      manzilRating: 5,
    },
    akhlaqRating: 'EXCELLENT',
  },
  {
    id: 'usr-student-2',
    admissionNo: 'MU-2023-0143',
    fullName: 'Fatima Kabir Ahmad',
    gender: 'FEMALE',
    dob: '2014-08-20',
    dateEnrolled: '2023-09-01',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-2',
    className: 'Tahfiz Halqa 2 (Intermediate Hifz)',
    guardianId: 'usr-parent-1',
    guardianName: 'Alhaji Kabir Ahmad',
    guardianPhone: '+234 803 987 6543',
    status: 'ACTIVE',
    hifzProgress: {
      currentJuz: 9,
      juzCompleted: 8,
      currentSurah: "Surah Al-A'raf",
      currentAyah: 120,
      completedSurahsCount: 22,
      tajweedRating: 4,
      sabkiRating: 4,
      manzilRating: 4,
    },
    akhlaqRating: 'EXCELLENT',
  },
  {
    id: 'usr-student-3',
    admissionNo: 'MU-2022-0089',
    fullName: 'Muhammad Isa Bello',
    gender: 'MALE',
    dob: '2011-03-10',
    dateEnrolled: '2022-09-01',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    guardianId: 'usr-parent-2',
    guardianName: 'Dr. Isa Bello Kano',
    guardianPhone: '+234 802 333 4444',
    status: 'ACTIVE',
    hifzProgress: {
      currentJuz: 28,
      juzCompleted: 27,
      currentSurah: 'Surah Al-Mulk',
      currentAyah: 12,
      completedSurahsCount: 95,
      tajweedRating: 5,
      sabkiRating: 5,
      manzilRating: 5,
    },
    akhlaqRating: 'EXCELLENT',
  },
  {
    id: 'usr-student-4',
    admissionNo: 'MU-2024-0210',
    fullName: 'Zainab Umar Faruq',
    gender: 'FEMALE',
    dob: '2015-11-02',
    dateEnrolled: '2024-01-10',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    classId: 'cls-primary-4',
    className: 'Primary 4 Islamiyya',
    guardianId: 'usr-admin-1',
    guardianName: 'Malam Umar Faruq',
    guardianPhone: '+234 803 123 4567',
    status: 'ACTIVE',
    hifzProgress: {
      currentJuz: 4,
      juzCompleted: 3,
      currentSurah: 'Surah An-Nisa',
      currentAyah: 24,
      completedSurahsCount: 37,
      tajweedRating: 4,
      sabkiRating: 4,
      manzilRating: 3,
    },
    akhlaqRating: 'VERY_GOOD',
  },
  {
    id: 'usr-student-5',
    admissionNo: 'MU-2023-0177',
    fullName: 'Yusuf Abdullahi Danbatta',
    gender: 'MALE',
    dob: '2010-01-15',
    dateEnrolled: '2023-09-01',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    classId: 'cls-secondary-2',
    className: 'Secondary 2 Islamiyya',
    guardianId: 'usr-parent-3',
    guardianName: 'Engr. Abdullahi Danbatta',
    guardianPhone: '+234 806 777 8888',
    status: 'ACTIVE',
    hifzProgress: {
      currentJuz: 15,
      juzCompleted: 14,
      currentSurah: 'Surah Al-Hijr',
      currentAyah: 80,
      completedSurahsCount: 41,
      tajweedRating: 4,
      sabkiRating: 3,
      manzilRating: 4,
    },
    akhlaqRating: 'VERY_GOOD',
  },
];

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: 'usr-teacher-asm-1',
    staffNo: 'MU-T-101',
    full_name_english: 'Abdullahi Sulaiman Abubakar',
    full_name_arabic: 'عبدالله سليمان أبوبكر',
    fullName: 'Abdullahi Sulaiman Abubakar',
    email: 'abdullahi.abubakar@markazuumar.edu.ng',
    phone: '+234 803 111 2233',
    qualification: 'B.A. Quranic Studies (Ijazah Hafs & Warsh)',
    specialization: "Qur'an Memorization & Tajweed",
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-1'],
    subjectsAssigned: ["Qur'an Memorization & Tajweed"],
    dateJoined: '2022-01-15',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-2',
    staffNo: 'MU-T-102',
    full_name_english: 'Muhammad Sani Luqman',
    full_name_arabic: 'محمد ثاني لقمان',
    fullName: 'Muhammad Sani Luqman',
    email: 'muhammad.luqman@markazuumar.edu.ng',
    phone: '+234 803 222 3344',
    qualification: 'B.A. Islamic Law (Madinah)',
    specialization: 'Fiqh & Hadith',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-2'],
    subjectsAssigned: ['Fiqh (Islamic Jurisprudence)'],
    dateJoined: '2022-03-10',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-3',
    staffNo: 'MU-T-103',
    full_name_english: "Abdullahi Da'i Muhammad",
    full_name_arabic: 'عبدالله داعى محمد',
    fullName: "Abdullahi Da'i Muhammad",
    email: 'abdullahi.dai@markazuumar.edu.ng',
    phone: '+234 803 333 4455',
    qualification: 'B.A. Arabic Language & Literature',
    specialization: 'Arabic Grammar & Nahw',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-3'],
    subjectsAssigned: ['Arabic Grammar & Nahw'],
    dateJoined: '2022-05-20',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-4',
    staffNo: 'MU-T-104',
    full_name_english: 'Yusuf Sanusi',
    full_name_arabic: 'يوسف سنوسي',
    fullName: 'Yusuf Sanusi',
    email: 'yusuf.sanusi@markazuumar.edu.ng',
    phone: '+234 803 444 5566',
    qualification: 'B.Ed Islamic Studies',
    specialization: 'Seerah & Aqeedah',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-4'],
    subjectsAssigned: ['Seerah (Prophetic Biography)'],
    dateJoined: '2023-01-08',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-5',
    staffNo: 'MU-T-105',
    full_name_english: 'Ammar Munir Ibrahim',
    full_name_arabic: 'عمار منير إبراهيم',
    fullName: 'Ammar Munir Ibrahim',
    email: 'ammar.ibrahim@markazuumar.edu.ng',
    phone: '+234 803 555 6677',
    qualification: 'B.A. Usul ad-Din (Al-Azhar)',
    specialization: 'Hadith Studies',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-5'],
    subjectsAssigned: ['Hadith Studies & Mustalah'],
    dateJoined: '2023-02-14',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-6',
    staffNo: 'MU-T-106',
    full_name_english: 'Fatima Abdulhadi',
    full_name_arabic: 'فاطمة عبد الهادي',
    fullName: 'Fatima Abdulhadi',
    email: 'fatima.abdulhadi@markazuumar.edu.ng',
    phone: '+234 803 666 7788',
    qualification: 'B.A. Islamic Education (BUK)',
    specialization: 'Akhlaq & Tajweed for Girls',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-6'],
    subjectsAssigned: ['Akhlaq & Adab (Islamic Conduct)'],
    dateJoined: '2023-04-12',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-7',
    staffNo: 'MU-T-107',
    full_name_english: 'Amina Ali',
    full_name_arabic: 'آمنة علي',
    fullName: 'Amina Ali',
    email: 'amina.ali@markazuumar.edu.ng',
    phone: '+234 803 777 8899',
    qualification: 'B.A. Arabic & Islamic Studies',
    specialization: 'Quran Memorization & Tafseer',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-7'],
    subjectsAssigned: ["Qur'an Memorization & Tajweed"],
    dateJoined: '2023-06-01',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-8',
    staffNo: 'MU-T-108',
    full_name_english: 'Hasana Ali',
    full_name_arabic: 'حسنة علي',
    fullName: 'Hasana Ali',
    email: 'hasana.ali@markazuumar.edu.ng',
    phone: '+234 803 888 9900',
    qualification: 'B.Ed Language Studies',
    specialization: 'Arabic Literacy & Hifz',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-8'],
    subjectsAssigned: ['Arabic Grammar & Nahw'],
    dateJoined: '2023-08-19',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-asm-9',
    staffNo: 'MU-T-109',
    full_name_english: "Usama Rabi'",
    full_name_arabic: 'أسامة رابع',
    fullName: "Usama Rabi'",
    email: 'usama.rabi@markazuumar.edu.ng',
    phone: '+234 803 999 0011',
    qualification: 'B.A. Shariah & Islamic Jurisprudence',
    specialization: 'Fiqh & Qiraat',
    programmeIds: ['prog-01'],
    classesAssigned: ['cls-asm-9'],
    subjectsAssigned: ['Fiqh (Islamic Jurisprudence)'],
    dateJoined: '2023-10-05',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-1',
    staffNo: 'MU-T-001',
    full_name_english: 'Ustaz Abubakar Sadiq',
    full_name_arabic: 'أستاذ أبوبكر الصديق',
    fullName: 'Ustaz Abubakar Sadiq',
    email: 'elmuaztechnologiesltd@gmail.com',
    phone: '+234 802 234 5678',
    qualification: 'B.A. Islamic Studies (Al-Azhar University), Ijazah in 10 Qira\'at',
    specialization: "Qur'an Memorization & Tajweed Rules",
    programmeIds: ['prog-02', 'prog-01'],
    classesAssigned: ['cls-tahfiz-1', 'cls-asm-1'],
    subjectsAssigned: ["Qur'an Memorization & Tajweed", 'Arabic Grammar & Nahw'],
    dateJoined: '2020-08-15',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-2',
    staffNo: 'MU-T-002',
    full_name_english: 'Ustaz Usman Danfodio',
    full_name_arabic: 'أستاذ عثمان دَن فودي',
    fullName: 'Ustaz Usman Danfodio',
    email: 'usman.danfodio@markazuumar.edu.ng',
    phone: '+234 803 456 7890',
    qualification: 'B.A. Shariah (Islamic University of Madinah)',
    specialization: 'Fiqh & Hadith Sciences',
    programmeIds: ['prog-02'],
    classesAssigned: ['cls-tahfiz-2'],
    subjectsAssigned: ['Fiqh (Islamic Jurisprudence)', 'Hadith Studies & Mustalah'],
    dateJoined: '2021-01-10',
    status: 'ACTIVE',
  },
  {
    id: 'usr-teacher-3',
    staffNo: 'MU-T-003',
    full_name_english: 'Malama Aishatu Bello',
    full_name_arabic: 'معلمة عائشة بيلو',
    fullName: 'Malama Aishatu Bello',
    email: 'aishatu.bello@markazuumar.edu.ng',
    phone: '+234 805 678 9012',
    qualification: 'B.Ed Language & Islamic Education (BUK Kano)',
    specialization: 'Seerah & Islamic Conduct',
    programmeIds: ['prog-03', 'prog-04'],
    classesAssigned: ['cls-primary-4', 'cls-matan-1'],
    subjectsAssigned: ['Seerah (Prophetic Biography)', 'Akhlaq & Adab (Islamic Conduct)'],
    dateJoined: '2022-09-01',
    status: 'ACTIVE',
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 'subj-01',
    name: "Qur'an Memorization & Tajweed",
    nameEnglish: "Qur'an Memorization & Tajweed",
    arabicName: 'حفظ القرآن والتجويد',
    code: 'TQZ101',
    category: 'TAHFIZ',
    description: 'Comprehensive Hifz, Muraja\'ah, Makharij al-Huruf and Rules of Tajweed.',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    classId: 'cls-asm-1',
    className: 'Dar Abu Bakr As-Siddiq',
    status: 'ACTIVE',
    displayOrder: 1,
  },
  {
    id: 'subj-02',
    name: 'Hadith & Sunnah Studies',
    nameEnglish: 'Hadith & Sunnah Studies',
    arabicName: 'دراسات الحديث والسنة',
    code: 'HDS101',
    category: 'ISLAMIC',
    description: '40 Hadith An-Nawawi, prophetic traditions and moral applications.',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    classId: 'cls-asm-1',
    className: 'Dar Abu Bakr As-Siddiq',
    status: 'ACTIVE',
    displayOrder: 2,
  },
  {
    id: 'subj-03',
    name: 'Fiqh (Islamic Jurisprudence)',
    nameEnglish: 'Fiqh (Islamic Jurisprudence)',
    arabicName: 'الفقه الإسلامي',
    code: 'FQH101',
    category: 'ISLAMIC',
    description: 'Essentials of Taharah, Salah, Sawm, and everyday Islamic rulings.',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    classId: 'cls-primary-4',
    className: 'Primary 4 Islamiyya',
    status: 'ACTIVE',
    displayOrder: 1,
  },
  {
    id: 'subj-04',
    name: 'Arabic Grammar & Nahw',
    nameEnglish: 'Arabic Grammar & Nahw',
    arabicName: 'النحو والقواعد العربية',
    code: 'ARB101',
    category: 'GENERAL',
    description: 'Classical Arabic sentence parsing (I\'rab) and vocabulary building.',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    classId: 'cls-primary-4',
    className: 'Primary 4 Islamiyya',
    status: 'ACTIVE',
    displayOrder: 2,
  },
  {
    id: 'subj-05',
    name: 'Seerah & Islamic Conduct',
    nameEnglish: 'Seerah & Islamic Conduct',
    arabicName: 'السيرة النبوية والآداب',
    code: 'SRH101',
    category: 'ISLAMIC',
    description: 'Life of Prophet Muhammad (SAW) and Islamic character building (Akhlaq).',
    programmeId: 'prog-03',
    programmeName: 'Islamiyyah',
    classId: 'cls-secondary-2',
    className: 'Secondary 2 Islamiyya',
    status: 'ACTIVE',
    displayOrder: 1,
  },
  {
    id: 'subj-06',
    name: 'Tafsir Al-Qur\'an',
    nameEnglish: 'Tafsir Al-Qur\'an',
    arabicName: 'تفسير القرآن الكريم',
    code: 'TFS101',
    category: 'TAHFIZ',
    description: 'Exegetical commentary and contextual meanings of memorized Surahs.',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    status: 'ACTIVE',
    displayOrder: 1,
  },
];

export const MOCK_TEACHER_ASSIGNMENTS = [
  {
    id: 'ta-01',
    teacherId: 'usr-teacher-1',
    programmeId: 'prog-01',
    classId: 'cls-asm-1',
    subjectIds: ['subj-01', 'subj-02'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ta-02',
    teacherId: 'usr-teacher-1',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    subjectIds: ['subj-06'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ta-03',
    teacherId: 'usr-teacher-2',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-2',
    subjectIds: ['subj-06', 'subj-02'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ta-04',
    teacherId: 'usr-teacher-3',
    programmeId: 'prog-03',
    classId: 'cls-primary-4',
    subjectIds: ['subj-03', 'subj-04'],
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_PARENTS: Parent[] = [
  {
    id: 'usr-parent-1',
    fullName: 'Alhaji Kabir Ahmad',
    email: 'kabir.ahmad@gmail.com',
    phone: '+234 803 987 6543',
    occupation: 'Senior Commercial Merchant',
    address: 'No. 45 Sharada Phase 2, Kano State',
    wardsCount: 2,
    wardIds: ['usr-student-1', 'usr-student-2'],
  },
  {
    id: 'usr-parent-2',
    fullName: 'Dr. Isa Bello Kano',
    email: 'isa.bello@kanopoly.edu.ng',
    phone: '+234 802 333 4444',
    occupation: 'University Lecturer',
    address: 'Gwale Quarter, Kano City',
    wardsCount: 1,
    wardIds: ['usr-student-3'],
  },
  {
    id: 'usr-parent-3',
    fullName: 'Engr. Abdullahi Danbatta',
    email: 'danbatta.engr@yahoo.com',
    phone: '+234 806 777 8888',
    occupation: 'Civil Engineer',
    address: 'Danbatta GRA, Kano State',
    wardsCount: 1,
    wardIds: ['usr-student-5'],
  },
];

export const MOCK_TAHFIZ_RECORDS: TahfizRecord[] = [
  {
    id: 'tahfiz-log-1',
    date: '2026-08-01',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    classId: 'cls-tahfiz-1',
    teacherId: 'usr-teacher-1',
    hifzSurah: 'Surah Al-Kahf',
    hifzFromAyah: 40,
    hifzToAyah: 55,
    hifzPages: 1.5,
    currentJuz: 15,
    sabkiSurah: 'Surah Al-Isra (Complete)',
    sabkiRating: 5,
    manzilJuz: 14,
    manzilRating: 5,
    tajweedErrorsCount: 1,
    teacherNotes: 'Masha-Allah! Excellent recitation with clear Makharij and strong Hifz retention.',
  },
  {
    id: 'tahfiz-log-2',
    date: '2026-07-31',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    classId: 'cls-tahfiz-1',
    teacherId: 'usr-teacher-1',
    hifzSurah: 'Surah Al-Kahf',
    hifzFromAyah: 25,
    hifzToAyah: 39,
    hifzPages: 1.5,
    currentJuz: 15,
    sabkiSurah: 'Surah An-Nahl',
    sabkiRating: 4,
    manzilJuz: 13,
    manzilRating: 5,
    tajweedErrorsCount: 2,
    teacherNotes: 'Pay close attention to Ghunna and Idgham rules in Ayah 34.',
  },
  {
    id: 'tahfiz-log-3',
    date: '2026-08-01',
    studentId: 'usr-student-2',
    studentName: 'Fatima Kabir Ahmad',
    classId: 'cls-tahfiz-2',
    teacherId: 'usr-teacher-2',
    hifzSurah: "Surah Al-A'raf",
    hifzFromAyah: 110,
    hifzToAyah: 125,
    hifzPages: 1.0,
    currentJuz: 9,
    sabkiSurah: 'Surah Al-Anfal',
    sabkiRating: 4,
    manzilJuz: 7,
    manzilRating: 4,
    tajweedErrorsCount: 2,
    teacherNotes: 'Good effort on Sabki. Review the ending of Ayah 118 before tomorrow\'s lesson.',
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    date: '2026-08-01',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Juz 1-10)',
    teacherId: 'usr-teacher-1',
    status: 'PRESENT',
    remarks: 'Arrived early before Fajr Halqa',
  },
  {
    id: 'att-02',
    date: '2026-08-01',
    studentId: 'usr-student-2',
    studentName: 'Fatima Kabir Ahmad',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-2',
    className: 'Tahfiz Halqa 2 (Juz 11-20)',
    teacherId: 'usr-teacher-2',
    status: 'PRESENT',
    remarks: 'On time',
  },
  {
    id: 'att-03',
    date: '2026-08-01',
    studentId: 'usr-student-3',
    studentName: 'Muhammad Isa Bello',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Juz 1-10)',
    teacherId: 'usr-teacher-1',
    status: 'PRESENT',
    remarks: 'Active participant',
  },
  {
    id: 'att-04',
    date: '2026-08-01',
    studentId: 'usr-student-4',
    studentName: 'Zainab Umar Faruq',
    programmeId: 'prog-03',
    classId: 'cls-primary-4',
    className: 'Islamiyya Primary 4',
    teacherId: 'usr-teacher-3',
    status: 'LATE',
    remarks: '15 minutes late due to traffic',
  },
  {
    id: 'att-05',
    date: '2026-08-01',
    studentId: 'usr-student-5',
    studentName: 'Yusuf Abdullahi Danbatta',
    programmeId: 'prog-04',
    classId: 'cls-secondary-2',
    className: 'Islamiyya Secondary 2',
    teacherId: 'usr-teacher-1',
    status: 'MEDICAL_LEAVE',
    remarks: 'Medical leave approved by admin',
  },
];

export const MOCK_TIMETABLE: TimetablePeriod[] = [
  {
    id: 'tp-01',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Juz 1-10)',
    subjectId: 'subj-06',
    subjectName: "Hifz & Revision (Qur'an)",
    teacherId: 'usr-teacher-1',
    teacherName: 'Ustaz Ahmad Muhammad',
    dayOfWeek: 'MONDAY',
    startTime: '07:30 AM',
    endTime: '09:00 AM',
    room: 'Halqa Room A1',
  },
  {
    id: 'tp-02',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Juz 1-10)',
    subjectId: 'subj-02',
    subjectName: 'Tajweed Rules & Recitation',
    teacherId: 'usr-teacher-1',
    teacherName: 'Ustaz Ahmad Muhammad',
    dayOfWeek: 'MONDAY',
    startTime: '09:15 AM',
    endTime: '10:30 AM',
    room: 'Halqa Room A1',
  },
  {
    id: 'tp-03',
    programmeId: 'prog-01',
    classId: 'cls-asm-1',
    className: 'Asubah Halqa 1',
    subjectId: 'subj-01',
    subjectName: 'Tahfiz Juz 1-5 & Tajweed',
    teacherId: 'usr-teacher-1',
    teacherName: 'Ustaz Ahmad Muhammad',
    dayOfWeek: 'TUESDAY',
    startTime: '06:00 AM',
    endTime: '07:30 AM',
    room: 'Mosque Main Wing',
  },
  {
    id: 'tp-04',
    programmeId: 'prog-03',
    classId: 'cls-primary-4',
    className: 'Islamiyya Primary 4',
    subjectId: 'subj-03',
    subjectName: 'Islamic Studies & Fiqh',
    teacherId: 'usr-teacher-3',
    teacherName: 'Malam Isa Alkasim',
    dayOfWeek: 'MONDAY',
    startTime: '10:45 AM',
    endTime: '12:00 PM',
    room: 'Classroom 4B',
  },
  {
    id: 'tp-05',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-2',
    className: 'Tahfiz Halqa 2 (Juz 11-20)',
    subjectId: 'subj-06',
    subjectName: "Hifz & Revision (Qur'an)",
    teacherId: 'usr-teacher-2',
    teacherName: 'Mallama Ruqayyah Usman',
    dayOfWeek: 'MONDAY',
    startTime: '07:30 AM',
    endTime: '09:00 AM',
    room: 'Halqa Room B2',
  },
];

export const MOCK_DIRECT_MESSAGES: DirectMessage[] = [
  {
    id: 'msg-01',
    senderId: 'usr-teacher-1',
    senderName: 'Ustaz Ahmad Muhammad',
    senderRole: 'TEACHER',
    recipientStudentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    parentPhone: '+234 803 987 6543',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Juz 1-10)',
    messageType: 'TAHFIZ_REMINDER',
    subject: 'Hifz Revision Target for Surah Al-Kahf',
    content: 'Assalamu Alaikum Ibrahim, please prepare Ayah 40-70 of Surah Al-Kahf for tomorrow morning\'s Sabki presentation. Ensure tajweed rule review for Ikhfa and Idgham.',
    isRead: false,
    createdAt: '2026-08-02T14:30:00Z',
  },
  {
    id: 'msg-02',
    senderId: 'usr-teacher-1',
    senderName: 'Ustaz Ahmad Muhammad',
    senderRole: 'TEACHER',
    recipientStudentId: 'usr-student-3',
    studentName: 'Muhammad Isa Bello',
    parentPhone: '+234 802 333 4444',
    programmeId: 'prog-02',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Juz 1-10)',
    messageType: 'HOMEWORK',
    subject: 'Tajweed Assignment: Rules of Noon Sakinah',
    content: 'Kindly complete exercise 3 in the Tajweed workbook on page 42 before Wednesday morning session.',
    isRead: true,
    createdAt: '2026-08-01T09:15:00Z',
  },
];

export const DEFAULT_ASSESSMENT_CONFIG: AssessmentConfig = {
  id: 'cfg-01',
  session: '1447/1448 AH (2025/2026 AD)',
  term: 'Term 2',
  enableAssignment: true,
  maxAssignment: 10,
  enableCa1: true,
  maxCa1: 15,
  enableCa2: true,
  maxCa2: 15,
  enableTest: true,
  maxTest: 10,
  enableProject: false,
  maxProject: 10,
  enablePractical: false,
  maxPractical: 10,
  enableExam: true,
  maxExam: 50,
  passMark: 40,
  calcPosition: true,
  gradingScale: [
    { grade: 'A', minScore: 75, maxScore: 100, remark: 'Distinction' },
    { grade: 'B', minScore: 60, maxScore: 74.99, remark: 'Very Good' },
    { grade: 'C', minScore: 50, maxScore: 59.99, remark: 'Good' },
    { grade: 'D', minScore: 40, maxScore: 49.99, remark: 'Pass' },
    { grade: 'F', minScore: 0, maxScore: 39.99, remark: 'Fail' },
  ],
};

export const MOCK_RESULT_SUBMISSIONS: ResultApprovalSubmission[] = [
  {
    id: 'sub-01',
    teacherId: 'usr-teacher-1',
    teacherName: 'Ustaz Abubakar Sadiq',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    subjectId: 'subj-01',
    subjectName: "Qur'an Memorization & Tajweed",
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    totalStudents: 25,
    completedRecords: 25,
    missingScores: 0,
    classAverage: 88.5,
    highestScore: 98,
    lowestScore: 74,
    status: 'APPROVED',
    adminComments: 'Verified and approved for terminal report card generation.',
    submittedAt: '2026-07-25T10:00:00Z',
    reviewedAt: '2026-07-26T14:30:00Z',
    reviewedBy: 'Malam Umar Faruq (Principal)',
  },
  {
    id: 'sub-02',
    teacherId: 'usr-teacher-2',
    teacherName: 'Ustaz Usman Danfodio',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-2',
    className: 'Tahfiz Halqa 2 (Intermediate Hifz)',
    subjectId: 'subj-02',
    subjectName: 'Fiqh (Islamic Jurisprudence)',
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    totalStudents: 20,
    completedRecords: 18,
    missingScores: 2,
    classAverage: 76.2,
    highestScore: 92,
    lowestScore: 58,
    status: 'PENDING',
    adminComments: undefined,
    submittedAt: '2026-08-01T16:20:00Z',
  },
];

export const MOCK_GRADES: GradeRecord[] = [
  {
    id: 'grd-01',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    admissionNo: 'MU-2023-0142',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    subjectId: 'subj-01',
    subjectName: "Qur'an Memorization & Tajweed",
    teacherId: 'usr-teacher-1',
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    assignmentScore: 10,
    ca1Score: 14,
    ca2Score: 15,
    testScore: 9,
    examScore: 48,
    totalScore: 96,
    grade: 'A',
    remarks: 'Outstanding performance in Hifz and Tajweed recitation.',
    status: 'APPROVED',
    submissionId: 'sub-01',
    approvedAt: '2026-07-26T14:30:00Z',
    approvedBy: 'Malam Umar Faruq (Principal)',
  },
  {
    id: 'grd-02',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    admissionNo: 'MU-2023-0142',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    subjectId: 'subj-02',
    subjectName: 'Fiqh (Islamic Jurisprudence)',
    teacherId: 'usr-teacher-1',
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    assignmentScore: 9,
    ca1Score: 13,
    ca2Score: 14,
    testScore: 8,
    examScore: 44,
    totalScore: 88,
    grade: 'A',
    remarks: 'Excellent comprehension of Taharah and Salah rulings.',
    status: 'APPROVED',
    submissionId: 'sub-01',
    approvedAt: '2026-07-26T14:30:00Z',
    approvedBy: 'Malam Umar Faruq (Principal)',
  },
  {
    id: 'grd-03',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    admissionNo: 'MU-2023-0142',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    subjectId: 'subj-03',
    subjectName: 'Hadith Studies & Mustalah',
    teacherId: 'usr-teacher-1',
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    assignmentScore: 9,
    ca1Score: 13,
    ca2Score: 14,
    testScore: 8,
    examScore: 45,
    totalScore: 89,
    grade: 'A',
    remarks: 'Accurate memorization of Nawawi Hadiths with explanations.',
    status: 'APPROVED',
    submissionId: 'sub-01',
    approvedAt: '2026-07-26T14:30:00Z',
    approvedBy: 'Malam Umar Faruq (Principal)',
  },
  {
    id: 'grd-04',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    admissionNo: 'MU-2023-0142',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    subjectId: 'subj-06',
    subjectName: 'Arabic Grammar & Nahw',
    teacherId: 'usr-teacher-1',
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    assignmentScore: 8,
    ca1Score: 12,
    ca2Score: 13,
    testScore: 7,
    examScore: 42,
    totalScore: 82,
    grade: 'A',
    remarks: 'Good grasp of sentence structures.',
    status: 'APPROVED',
    submissionId: 'sub-01',
    approvedAt: '2026-07-26T14:30:00Z',
    approvedBy: 'Malam Umar Faruq (Principal)',
  },
  {
    id: 'grd-05',
    studentId: 'usr-student-1',
    studentName: 'Ibrahim Kabir Ahmad',
    admissionNo: 'MU-2023-0142',
    programmeId: 'prog-02',
    programmeName: 'Super Markaz',
    classId: 'cls-tahfiz-1',
    className: 'Tahfiz Halqa 1 (Advanced Hifz)',
    subjectId: 'subj-08',
    subjectName: 'Mathematics',
    teacherId: 'usr-teacher-1',
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    assignmentScore: 8,
    ca1Score: 12,
    ca2Score: 13,
    testScore: 7,
    examScore: 39,
    totalScore: 79,
    grade: 'B',
    remarks: 'Good progress. Needs practice on fractions and word problems.',
    status: 'APPROVED',
    submissionId: 'sub-01',
    approvedAt: '2026-07-26T14:30:00Z',
    approvedBy: 'Malam Umar Faruq (Principal)',
  },
  {
    id: 'grd-06',
    studentId: 'usr-student-2',
    studentName: 'Fatima Kabir Ahmad',
    classId: 'cls-tahfiz-2',
    subjectId: 'subj-01',
    subjectName: "Qur'an Memorization & Tajweed",
    term: 'Term 2',
    session: '1447/1448 AH (2025/2026 AD)',
    ca1Score: 18,
    ca2Score: 18,
    examScore: 54,
    totalScore: 90,
    grade: 'A',
    remarks: 'Excellent Tajweed and consistent daily memorization.',
    status: 'APPROVED',
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'Annual Markazu Umar National Hifz & Tajweed Competition',
    content: 'We are pleased to announce the upcoming Annual Qur\'an Memorization Competition scheduled for next month. All students in Tahfiz Halqa 1 and 2 are encouraged to finalize their revision.',
    date: '2026-07-28',
    category: 'TAHFIZ',
    targetRole: 'ALL',
    author: 'Malam Umar Faruq (Principal)',
    pinned: true,
  },
  {
    id: 'ann-02',
    title: 'Mid-Term Parent-Teacher Association (PTA) General Meeting',
    content: 'The PTA meeting for Term 2 will take place on Saturday at 10:00 AM in the Main School Auditorium. Agenda includes student progress reviews and school development updates.',
    date: '2026-07-25',
    category: 'GENERAL',
    targetRole: 'PARENTS',
    author: 'School Administration',
    pinned: true,
  },
  {
    id: 'ann-03',
    title: 'Submission Deadline for Term 2 Continuous Assessment (CA2)',
    content: 'All teachers are kindly reminded to complete and submit CA2 grades on the portal before Friday midnight.',
    date: '2026-07-20',
    category: 'ACADEMIC',
    targetRole: 'TEACHERS',
    author: 'Examination Officer',
    pinned: false,
  },
];

import {
  CommunicationMessage,
  MessageTemplate,
  QueueItem,
  InAppNotification,
  CommunicationSettings,
} from '../types/communication';

export const MOCK_MESSAGE_TEMPLATES: MessageTemplate[] = [
  {
    id: 'tmpl-01',
    title: 'Holiday & Vacation Notice',
    category: 'HOLIDAY_NOTICE',
    subject: 'Official Notice: School Vacation & Holiday Schedule',
    content: 'Dear Parents & Guardians,\n\nAssalamu Alaikum. Please be informed that Markazu Umar School will close for the upcoming vacation starting from [Date]. Normal classes and Tahfiz sessions will resume on [Resume Date].\n\nWe encourage all students to maintain their daily Qur\'an revision during the break.\n\nJazakumullahu Khairan,\nManagement Office',
    defaultChannels: ['EMAIL', 'WHATSAPP', 'IN_APP', 'DASHBOARD'],
    isDefault: true,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'tmpl-02',
    title: 'PTA General Meeting Invitation',
    category: 'PTA_MEETING',
    subject: 'Invitation: Parent-Teacher Association (PTA) Meeting',
    content: 'Dear Respected Parent/Guardian,\n\nAssalamu Alaikum. You are cordially invited to the PTA Meeting scheduled for [Date] at 10:00 AM in the Main Auditorium.\n\nAgenda:\n1. Academic & Tahfiz progress overview\n2. Infrastructure development updates\n3. Interactive Q&A session\n\nYour presence is highly valued.',
    defaultChannels: ['EMAIL', 'WHATSAPP', 'IN_APP'],
    isDefault: true,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'tmpl-03',
    title: 'Term Examination Schedule & Guidelines',
    category: 'EXAMINATION_NOTICE',
    subject: 'Important: Term Final Examinations Timetable & Rules',
    content: 'Assalamu Alaikum,\n\nFinal Term Examinations will commence on [Exam Start Date]. Students are requested to adhere strictly to the timetable and ensure all Continuous Assessments (CA) are completed.\n\nBest of luck to all candidates.\nExamination Board',
    defaultChannels: ['EMAIL', 'WHATSAPP', 'DASHBOARD'],
    isDefault: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'tmpl-04',
    title: 'Ramadan Mubarak Greeting & Schedule Adjustment',
    category: 'HOLIDAY_NOTICE',
    subject: 'Ramadan Mubarak: Revised School & Tahfiz Timings',
    content: 'Ramadan Mubarak to our entire school community!\n\nDuring the holy month of Ramadan, school hours will be adjusted as follows:\n• Asubah & Magrib Sessions: Adjusted timings\n• Afternoon Classes: Conclude at 1:30 PM\n\nMay Allah accept our fasting and recitation.',
    defaultChannels: ['EMAIL', 'WHATSAPP', 'IN_APP', 'DASHBOARD'],
    isDefault: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'tmpl-05',
    title: 'Eid Greetings & Break Notice',
    category: 'HOLIDAY_NOTICE',
    subject: 'Eid Mubarak Announcement & Celebration Break',
    content: 'Taqabbalallahu Minna Wa Minkum! Eid Mubarak to all students, parents, teachers, and staff.\n\nThe school will observe an Eid holiday break. Session resumes on [Resume Date].',
    defaultChannels: ['EMAIL', 'WHATSAPP', 'IN_APP'],
    isDefault: true,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'tmpl-06',
    title: 'New Admission Announcement',
    category: 'ADMISSION_NOTICE',
    subject: 'Admissions Open for New Academic Session',
    content: 'Assalamu Alaikum. Admissions are now officially open for the upcoming session across our programmes:\n1. Asubah & Magrib\n2. Super Markaz\n3. Islamiyyah\n4. Matan Aure\n\nApply online or visit the admin office.',
    defaultChannels: ['EMAIL', 'DASHBOARD'],
    isDefault: true,
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'tmpl-07',
    title: 'Official Terminal Report Sheet Delivery',
    category: 'REPORT_SHEET',
    subject: 'Official Terminal Progress Report Card',
    content: 'Dear Parent/Guardian,\n\nAssalamu Alaikum. Please find attached the official Terminal Academic & Tahfiz Progress Report Card for your ward(s).\n\nThank you for your continuous support.\nManagement Office',
    defaultChannels: ['EMAIL', 'WHATSAPP', 'IN_APP'],
    isDefault: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
];

export const MOCK_COMMUNICATIONS: CommunicationMessage[] = [
  {
    id: 'comm-101',
    title: 'Annual Markazu Umar National Hifz & Tajweed Competition',
    type: 'EVENT_NOTICE',
    priority: 'IMPORTANT',
    channels: ['EMAIL', 'WHATSAPP', 'IN_APP', 'DASHBOARD'],
    recipientType: 'ENTIRE_SCHOOL',
    subject: 'Official Announcement: Annual Qur\'an Competition',
    content: 'We are pleased to announce the upcoming Annual Qur\'an Memorization Competition scheduled for next month. All students in Tahfiz Halqa 1 and 2 are encouraged to finalize their revision.',
    plainContent: 'Annual Qur\'an Memorization Competition scheduled for next month.',
    senderId: 'usr-admin-1',
    senderName: 'Malam Umar Faruq (Principal)',
    senderRole: 'ADMIN',
    status: 'SENT',
    sentAt: '2026-07-28T09:30:00Z',
    createdAt: '2026-07-28T09:00:00Z',
    stats: {
      totalRecipients: 45,
      emailCount: 45,
      whatsappCount: 40,
      notificationCount: 45,
      dashboardCount: 45,
      deliveredCount: 44,
      failedCount: 1,
      readCount: 38,
    },
  },
  {
    id: 'comm-102',
    title: 'Term 2 Final Terminal Report Sheets Published',
    type: 'REPORT_SHEET',
    priority: 'URGENT',
    channels: ['EMAIL', 'WHATSAPP', 'IN_APP'],
    recipientType: 'PARENTS',
    programmeId: 'prog-01',
    programmeName: 'Asubah & Magrib',
    subject: 'Terminal Academic & Tahfiz Progress Report Card Dispatch',
    content: 'Assalamu Alaikum. The Term 2 report cards for Asubah & Magrib students have been compiled, verified, and dispatched.',
    senderId: 'usr-superadmin-1',
    senderName: 'Dr. Abubakar Umar (Super Admin)',
    senderRole: 'SUPER_ADMIN',
    status: 'SENT',
    sentAt: '2026-07-30T14:00:00Z',
    createdAt: '2026-07-30T13:45:00Z',
    stats: {
      totalRecipients: 12,
      emailCount: 12,
      whatsappCount: 12,
      notificationCount: 12,
      dashboardCount: 0,
      deliveredCount: 12,
      failedCount: 0,
      readCount: 11,
    },
  },
];

export const MOCK_QUEUE_ITEMS: QueueItem[] = [
  {
    id: 'q-01',
    messageId: 'comm-101',
    messageTitle: 'Annual Markazu Umar National Hifz & Tajweed Competition',
    channel: 'WHATSAPP',
    recipientId: 'usr-parent-2',
    recipientName: 'Mallam Ibrahim Kabir',
    recipientContact: '+234 802 999 8877',
    recipientRole: 'PARENT',
    status: 'FAILED',
    errorTrace: 'WhatsApp API Gateway Timeout (HTTP 504)',
    attempts: 3,
    maxAttempts: 3,
    queuedAt: '2026-07-28T09:31:00Z',
    processedAt: '2026-07-28T09:34:00Z',
  },
  {
    id: 'q-02',
    messageId: 'comm-102',
    messageTitle: 'Term 2 Final Terminal Report Sheets Published',
    channel: 'EMAIL',
    recipientId: 'usr-parent-1',
    recipientName: 'Mallam Kabir Ahmad Musa',
    recipientContact: 'kabir.ahmad@gmail.com',
    recipientRole: 'PARENT',
    status: 'COMPLETED',
    attempts: 1,
    maxAttempts: 3,
    queuedAt: '2026-07-30T14:01:00Z',
    processedAt: '2026-07-30T14:01:05Z',
  },
];

export const MOCK_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-01',
    userId: 'usr-parent-1',
    title: 'Report Card Published: Ahmed & Fatima Kabir',
    body: 'The official Term 2 Report Cards for your wards Ahmed Kabir and Fatima Kabir have been published and delivered.',
    priority: 'URGENT',
    category: 'REPORT_SHEET',
    channels: ['IN_APP', 'EMAIL', 'WHATSAPP'],
    senderName: 'Management Office',
    read: false,
    pinned: true,
    isArchived: false,
    createdAt: '2026-07-30T14:02:00Z',
  },
  {
    id: 'notif-02',
    userId: 'usr-parent-1',
    title: 'Annual Hifz & Tajweed Competition Announcement',
    body: 'Registration for the Annual Qur\'an Memorization Competition is now open. Encourage your children to participate!',
    priority: 'IMPORTANT',
    category: 'EVENT_NOTICE',
    channels: ['IN_APP', 'DASHBOARD'],
    senderName: 'Malam Umar Faruq (Principal)',
    read: true,
    pinned: false,
    isArchived: false,
    createdAt: '2026-07-28T09:32:00Z',
  },
  {
    id: 'notif-03',
    userId: 'usr-teacher-1',
    title: 'CA2 Score Submission Reminder',
    body: 'Please complete and verify CA2 score entries for Dar Abu Bakr As-Siddiq before Friday midnight.',
    priority: 'IMPORTANT',
    category: 'EXAMINATION_NOTICE',
    channels: ['IN_APP'],
    senderName: 'Examination Officer',
    read: false,
    pinned: true,
    isArchived: false,
    createdAt: '2026-07-20T11:00:00Z',
  },
];

export const MOCK_COMMUNICATION_SETTINGS: CommunicationSettings = {
  schoolEmail: 'info@markazuumar.edu.ng',
  replyToEmail: 'support@markazuumar.edu.ng',
  schoolWhatsApp: '+234 816 710 9421',
  defaultSignature: 'Management Office\nMarkazu Umar bn Al-Khattab Centre for Qur\'an Memorization and Islamic Studies - Daneji',
  footerText: 'Official Communication • Markazu Umar bn Al-Khattab Centre for Qur\'an Memorization and Islamic Studies - Daneji • Kano, Nigeria',
  schoolLogo: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=150',
  enableEmailService: true,
  enableWhatsAppService: true,
  enableInAppService: true,
  enableDashboardService: true,
};

