services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://mssms_user:mssms_secure_pass_1447@postgres:5432/mssms_db?schema=public
      - NODE_ENV=production
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_USER=${SMTP_USER:-markazuumarbnkhaddabdaneji@gmail.com}
      - SMTP_PASS=${SMTP_PASS:-dfwsrewunzjvchxg}
      - EMAIL_MODE=${EMAIL_MODE:-production}
      - DEVELOPMENT_EMAIL_RECIPIENT=${DEVELOPMENT_EMAIL_RECIPIENT:-markazuumarbnkhaddabdaneji@gmail.com}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://mubkdaneji.com}
      - SYSTEM_API_SECRET=${SYSTEM_API_SECRET:-MARKAZU_UMAR_INTERNAL_SECRET_2026}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mssms_user
      POSTGRES_PASSWORD: mssms_secure_pass_1447
      POSTGRES_DB: mssms_db
    # PostgreSQL is accessed internally by app via docker network, no public host port needed
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

networks:
  default:
    driver: bridge
